spring:
  datasource:
    url: jdbc:postgresql://containers-us-west-158.railway.app:5802/railway
    username: postgres
    password: AepCRIn2cDSIRTPg0vqj
    name: railway

  sql:
    init:
      mode: always